### ISSUE TITLE
CRFS example

### ISSUE THREAD

**Issue by mikenedodai** [Sam4uk/CRSF#1]
Can you provide an example of a basic use of the library with arduino for reading data from elrs receiver?

**Comment by Sam4uk** [comment]
Yes, there will be usage examples in the library update
I am focused on a project that will use this library.
Sorry for posting without documentation
The library is currently under testing.
You can use this example for parsing signals from the remote control.

Так приклади будуть додані у оновленні бібліотеки.
Нині я окрім основної роботи зосерджений на проекті,
/  який використовуватиме цю бібліотеку.
Вибачте, що обпублікував без документації.
Ми ще проводимо тести на "залізі"
Ви можете коистуватись прикладом, наведеним нижче, для отримання сигналів від пульту

```cpp


#include <CrsfSerial.h>
#if defined(__AVR_ATmega2560__)
CrsfSerial                  
    crsf(Serial3, CRSF_BAUDRATE); //  receiver connect to Serial3
#else
#error NOT MEGA2560
#endif

void packetChannels();

void setup(){

crsf.begin();
crsf.onPacketChannels = &packetChannels;
}

void loop(){
crsf.loop();
}

void packetChannels(){
  for (auto ch{1}; ch <= CRSF_NUM_CHANNELS; ++ch) {
    Serial.print(crsf.getChannel(ch));
    if (ch != CRSF_NUM_CHANNELS)
      Serial.print(", ");
  }
  Serial.println();
}
```

**Comment by Sam4uk** [comment]
Added a simple example
