### ISSUE TITLE
License and attribution missing

### ISSUE THREAD

**Issue by josephduchesne** [Sam4uk/CRSF#2]
I came across this library looking for a non-GPL3 CRSF library, but while this copy lists the  CC0-1.0 license, it looks like it's a copy of the GPL3 library https://github.com/ZZ-Cat/CRSFforArduino . Forking it to just the Arduino library is fine under its original license, but the license and copyright should be corrected.

**Comment by Sam4uk** [comment]
@josephduchesne Please specify the specific file or location in the file that is a copy of the repository you mentioned.

**Comment by Sam4uk** [comment]
close
